### ISSUE TITLE
Chat copy past

### ISSUE THREAD

**Issue by diogomiguelfreire** [CodeIsJustLikeMagic/SummonerTrackerClientP#2]
Hey Would be nice if the timers showing on the left could be saved in the copy past, so we could past into chat and tell teammates the times. and you can also add a link at the end to advertise this tool. 
Great work

**Comment by CodeIsJustLikeMagic** [comment]
Hi, so by itself copying the text into your computers clipboard is super easy. The problem is that LoL doesn't let you paste anything into the ingame chat. So I feel like there is really no reason to automatically copy the text in the first place. 
The only altanative way to do this is to create a makro that types the text into the ingame chat. But I've heard that LoL doesn't like makros.
I don't understand what you mean when you say "a link to advertise this tool". If you want to share the overlay with your friends just send them the Github link?
